steps:

  # Run the app and dependencies in the background using docker-compose.
  - name: 'docker/compose:latest'
    args: ['up', '-d']

  # Build the Docker image.
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA', '.']
    env: ['PROJECT_ROOT=app']
    dir: 'app'

  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA', '.']
    env: ['PROJECT_ROOT=certbot']
    dir: 'certbot'

images: ['eu.gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA']
