steps:
  - name: 'docker/compose:1.19.0'
    args: ['up', '-d']
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA', '.']
images:
  - 'eu.gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'