steps:

  # Build the Docker image.
  - id: 'build webapp'
    name: gcr.io/cloud-builders/docker
    args: ['build', '-f', './app/Dockerfile', '-t', 'eu.gcr.io/$PROJECT_ID/https-nodejs_app', 'app/.']
    waitFor: ['-']

  - id: 'build webroot'
    name: gcr.io/cloud-builders/docker
    args: ['build', '-f', './certbot/Dockerfile', '-t', 'eu.gcr.io/$PROJECT_ID/https-nodejs_cerbot', 'certbot/.']
    waitFor: ['build webapp']

  # Run the app and dependencies in the background using docker-compose.
  - id: 'compose up'
    name: 'docker/compose:latest'
    args: ['up', '-d']
    env:
    - 'PROJECT_ID=$PROJECT_ID'
    waitFor: ['build webapp','build webroot']

images: 
  - 'eu.gcr.io/$PROJECT_ID/https-nodejs_app'
  - 'eu.gcr.io/$PROJECT_ID/https-nodejs_cerbot'
