version: '3'
services:

  app:
    # build: ./app
    # container_name: app
    image: eu.gcr.io/${PROJECT_ID}/https-nodejs_app
    ports:
      - "8080:8080"
      # - "80:8080"
      # - "443:443"
    restart: always
    volumes:
      - certbot-webroot-gkeprod:/app/public/.well-known
      - certbot-letsencrypt:/etc/letsencrypt

  certbot:
    # build: ./certbot
    # container_name: certbot
    image: eu.gcr.io/${PROJECT_ID}/https-nodejs_cerbot
    restart: always
    volumes:
      - certbot-webroot-gkeprod:/webroots/gkeprod.dev/.well-known
      - certbot-letsencrypt:/etc/letsencrypt

  # nginx:
  #   build: ./nginx
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   restart: always
  #   volumes:
  #     - certbot-webroot-gkeprod:/webroots/gkeprod.dev/.well-known
  #     - certbot-letsencrypt:/etc/letsencrypt

volumes:
  certbot-webroot-gkeprod:
  certbot-letsencrypt:

networks:
  default:
    external:
      name: cloudbuild
