version: '3'
services:

  app:
    build: ./app
    container_name: app
    ports:
      - "3000:3000"
      # - "80:3000"
      # - "443:443"
    restart: always
    volumes:
      - certbot-webroot-ethprod:/app/public/.well-known
      - certbot-letsencrypt:/etc/letsencrypt

  certbot:
    build: ./certbot
    container_name: certbot
    restart: always
    volumes:
      - certbot-webroot-ethprod:/webroots/ethprod.xyz/.well-known
      - certbot-letsencrypt:/etc/letsencrypt

  # nginx:
  #   build: ./nginx
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   restart: always
  #   volumes:
  #     - certbot-webroot-ethprod:/webroots/ethprod.xyz/.well-known
  #     - certbot-letsencrypt:/etc/letsencrypt

volumes:
  certbot-webroot-ethprod:
  certbot-letsencrypt:

networks:
  default:
    external:
      name: cloudbuild